# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spell_and_cantrip_display.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spell_and_cantrip_display(object):
    def setupUi(self, spell_and_cantrip_display):
        spell_and_cantrip_display.setObjectName("spell_and_cantrip_display")
        spell_and_cantrip_display.resize(825, 888)
        self.label = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label.setGeometry(QtCore.QRect(280, -20, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scrollArea_6 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_6.setGeometry(QtCore.QRect(270, 190, 221, 111))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.scrollArea_7 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_7.setGeometry(QtCore.QRect(270, 750, 221, 101))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 219, 99))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.scrollArea_9 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_9.setGeometry(QtCore.QRect(270, 610, 221, 111))
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_9)
        self.scrollArea_8 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_8.setGeometry(QtCore.QRect(30, 330, 221, 111))
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.scrollArea_12 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_12.setGeometry(QtCore.QRect(30, 610, 221, 111))
        self.scrollArea_12.setWidgetResizable(True)
        self.scrollArea_12.setObjectName("scrollArea_12")
        self.scrollAreaWidgetContents_12 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_12.setObjectName("scrollAreaWidgetContents_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_12)
        self.scrollArea_16 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_16.setGeometry(QtCore.QRect(270, 330, 221, 111))
        self.scrollArea_16.setWidgetResizable(True)
        self.scrollArea_16.setObjectName("scrollArea_16")
        self.scrollAreaWidgetContents_16 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_16.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_16.setObjectName("scrollAreaWidgetContents_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_16.setWidget(self.scrollAreaWidgetContents_16)
        self.scrollArea_15 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_15.setGeometry(QtCore.QRect(30, 470, 221, 111))
        self.scrollArea_15.setWidgetResizable(True)
        self.scrollArea_15.setObjectName("scrollArea_15")
        self.scrollAreaWidgetContents_15 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_15.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_15.setObjectName("scrollAreaWidgetContents_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_15.setWidget(self.scrollAreaWidgetContents_15)
        self.scrollArea_14 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_14.setGeometry(QtCore.QRect(30, 750, 221, 101))
        self.scrollArea_14.setWidgetResizable(True)
        self.scrollArea_14.setObjectName("scrollArea_14")
        self.scrollAreaWidgetContents_14 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_14.setGeometry(QtCore.QRect(0, 0, 219, 99))
        self.scrollAreaWidgetContents_14.setObjectName("scrollAreaWidgetContents_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_14)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_14.setWidget(self.scrollAreaWidgetContents_14)
        self.scrollArea_13 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_13.setGeometry(QtCore.QRect(270, 470, 221, 111))
        self.scrollArea_13.setWidgetResizable(True)
        self.scrollArea_13.setObjectName("scrollArea_13")
        self.scrollAreaWidgetContents_13 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_13.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_13.setObjectName("scrollAreaWidgetContents_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_13)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_13.setWidget(self.scrollAreaWidgetContents_13)
        self.scrollArea = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea.setGeometry(QtCore.QRect(540, 80, 261, 781))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 779))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.description_text = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.description_text.setGeometry(QtCore.QRect(0, 0, 261, 781))
        self.description_text.setReadOnly(True)
        self.description_text.setObjectName("description_text")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_3.setGeometry(QtCore.QRect(30, 310, 47, 21))
        self.label_3.setObjectName("label_3")
        self.edit_cantrip = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_cantrip.setGeometry(QtCore.QRect(210, 170, 41, 20))
        self.edit_cantrip.setObjectName("edit_cantrip")
        self.label_4 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_4.setGeometry(QtCore.QRect(640, 50, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.scrollArea_10 = QtWidgets.QScrollArea(spell_and_cantrip_display)
        self.scrollArea_10.setGeometry(QtCore.QRect(30, 190, 221, 111))
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollArea_10.setObjectName("scrollArea_10")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 219, 109))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_10)
        self.label_5 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_5.setGeometry(QtCore.QRect(270, 170, 47, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_6.setGeometry(QtCore.QRect(30, 450, 47, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_7.setGeometry(QtCore.QRect(270, 310, 47, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_8.setGeometry(QtCore.QRect(270, 450, 47, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_9.setGeometry(QtCore.QRect(270, 590, 47, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_10.setGeometry(QtCore.QRect(30, 590, 47, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_11.setGeometry(QtCore.QRect(30, 730, 47, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(spell_and_cantrip_display)
        self.label_12.setGeometry(QtCore.QRect(270, 730, 47, 21))
        self.label_12.setObjectName("label_12")
        self.edit_6 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_6.setGeometry(QtCore.QRect(450, 310, 41, 20))
        self.edit_6.setObjectName("edit_6")
        self.edit_5 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_5.setGeometry(QtCore.QRect(450, 170, 41, 20))
        self.edit_5.setObjectName("edit_5")
        self.edit_7 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_7.setGeometry(QtCore.QRect(450, 450, 41, 20))
        self.edit_7.setObjectName("edit_7")
        self.edit_8 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_8.setGeometry(QtCore.QRect(450, 590, 41, 20))
        self.edit_8.setObjectName("edit_8")
        self.edit_3 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_3.setGeometry(QtCore.QRect(210, 590, 41, 20))
        self.edit_3.setObjectName("edit_3")
        self.edit_1 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_1.setGeometry(QtCore.QRect(210, 310, 41, 20))
        self.edit_1.setObjectName("edit_1")
        self.edit_4 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_4.setGeometry(QtCore.QRect(210, 730, 41, 20))
        self.edit_4.setObjectName("edit_4")
        self.edit_2 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_2.setGeometry(QtCore.QRect(210, 450, 41, 20))
        self.edit_2.setObjectName("edit_2")
        self.edit_9 = QtWidgets.QPushButton(spell_and_cantrip_display)
        self.edit_9.setGeometry(QtCore.QRect(450, 730, 41, 20))
        self.edit_9.setObjectName("edit_9")
        self.groupBox = QtWidgets.QGroupBox(spell_and_cantrip_display)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 471, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(180, 20, 121, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(310, 20, 121, 16))
        self.label_15.setObjectName("label_15")
        self.spell_cast_ability = QtWidgets.QLabel(self.groupBox)
        self.spell_cast_ability.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.spell_cast_ability.setText("")
        self.spell_cast_ability.setObjectName("spell_cast_ability")
        self.spell_save_dc = QtWidgets.QLabel(self.groupBox)
        self.spell_save_dc.setGeometry(QtCore.QRect(210, 50, 41, 21))
        self.spell_save_dc.setText("")
        self.spell_save_dc.setObjectName("spell_save_dc")
        self.spell_attack_bonus = QtWidgets.QLabel(self.groupBox)
        self.spell_attack_bonus.setGeometry(QtCore.QRect(350, 50, 41, 21))
        self.spell_attack_bonus.setText("")
        self.spell_attack_bonus.setObjectName("spell_attack_bonus")

        self.retranslateUi(spell_and_cantrip_display)
        QtCore.QMetaObject.connectSlotsByName(spell_and_cantrip_display)

    def retranslateUi(self, spell_and_cantrip_display):
        _translate = QtCore.QCoreApplication.translate
        spell_and_cantrip_display.setWindowTitle(_translate("spell_and_cantrip_display", "Form"))
        self.label.setText(_translate("spell_and_cantrip_display", "Spells and Cantrips"))
        self.label_2.setText(_translate("spell_and_cantrip_display", "Cantrips"))
        self.label_3.setText(_translate("spell_and_cantrip_display", "Level 1"))
        self.edit_cantrip.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.label_4.setText(_translate("spell_and_cantrip_display", "Description"))
        self.label_5.setText(_translate("spell_and_cantrip_display", "Level 5"))
        self.label_6.setText(_translate("spell_and_cantrip_display", "Level 2"))
        self.label_7.setText(_translate("spell_and_cantrip_display", "Level 6"))
        self.label_8.setText(_translate("spell_and_cantrip_display", "Level 7"))
        self.label_9.setText(_translate("spell_and_cantrip_display", "Level 8"))
        self.label_10.setText(_translate("spell_and_cantrip_display", "Level 3"))
        self.label_11.setText(_translate("spell_and_cantrip_display", "Level 4"))
        self.label_12.setText(_translate("spell_and_cantrip_display", "Level 9"))
        self.edit_6.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_5.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_7.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_8.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_3.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_1.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_4.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_2.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.edit_9.setText(_translate("spell_and_cantrip_display", "Edit"))
        self.groupBox.setTitle(_translate("spell_and_cantrip_display", "Info"))
        self.label_13.setText(_translate("spell_and_cantrip_display", "Spell casting ability"))
        self.label_14.setText(_translate("spell_and_cantrip_display", "Spell save dc"))
        self.label_15.setText(_translate("spell_and_cantrip_display", "Spell attack bonus"))
